/**
 * GET /api/pets/photos — live listing of the Cloudinary Pets folder.
 *
 * Unlike the wedding/honeymoon galleries (frozen manifests generated by
 * scripts/generateGallery.js), the pets chapter grows for the rest of its
 * life, so it lists the folder at request time. The CDN caches the response
 * for 5 minutes (s-maxage), so a phone upload appears on the next visit
 * without a rebuild or deploy.
 *
 * Env: CLOUDINARY_API_SECRET (required; Vercel project settings).
 */

// .trim() throughout: pasted Vercel env values commonly carry a trailing
// newline, which would break Cloudinary's basic-auth credential match.
const CLOUD_NAME = (process.env.CLOUDINARY_CLOUD_NAME || "dbr3xp0bx").trim();
const API_KEY = (process.env.CLOUDINARY_API_KEY || "795228952549794").trim();
const PETS_FOLDER = (process.env.CLOUDINARY_PETS_FOLDER || "Pets").trim();

interface CloudinarySearchResource {
  public_id: string;
  secure_url: string;
  width: number;
  height: number;
  created_at: string;
  tags?: string[];
  context?: Record<string, string> & { custom?: Record<string, string> };
}

export default async function handler(
  req: { method?: string },
  res: {
    status: (code: number) => { json: (body: unknown) => void };
    setHeader: (name: string, value: string) => void;
  },
) {
  if (req.method && req.method !== "GET") {
    res.setHeader("Allow", "GET");
    return res.status(405).json({ error: "Method not allowed" });
  }

  const secret = process.env.CLOUDINARY_API_SECRET?.trim();
  if (!secret) {
    return res.status(500).json({ error: "CLOUDINARY_API_SECRET is not configured" });
  }

  const auth = Buffer.from(`${API_KEY}:${secret}`).toString("base64");
  const photos: unknown[] = [];
  let nextCursor: string | undefined;

  try {
    do {
      const response = await fetch(
        `https://api.cloudinary.com/v1_1/${CLOUD_NAME}/resources/search`,
        {
          method: "POST",
          headers: {
            Authorization: `Basic ${auth}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            expression: `folder:"${PETS_FOLDER}" AND resource_type:image`,
            max_results: 500,
            with_field: ["tags", "context"],
            sort_by: [{ created_at: "desc" }],
            ...(nextCursor ? { next_cursor: nextCursor } : {}),
          }),
        },
      );

      if (!response.ok) {
        const detail = await response.text();
        return res.status(502).json({ error: "Cloudinary search failed", detail });
      }

      const data = (await response.json()) as {
        resources?: CloudinarySearchResource[];
        next_cursor?: string;
      };

      for (const resource of data.resources || []) {
        // Caption lives in context metadata; the search API has returned it
        // both flat and nested under `custom` across versions, so check both
        // (same fallbacks as scripts/generateGallery.js).
        const context = resource.context || {};
        const caption =
          context.caption ||
          context.description ||
          context.custom?.caption ||
          context.custom?.description ||
          null;

        photos.push({
          id: resource.public_id,
          url: resource.secure_url,
          width: resource.width,
          height: resource.height,
          tags: resource.tags || [],
          caption,
          createdAt: resource.created_at,
        });
      }

      nextCursor = data.next_cursor;
    } while (nextCursor);
  } catch (error) {
    return res.status(502).json({
      error: "Cloudinary search failed",
      detail: error instanceof Error ? error.message : String(error),
    });
  }

  res.setHeader("Cache-Control", "s-maxage=300, stale-while-revalidate=3600");
  return res.status(200).json({ photos });
}
